# Generated by Django 3.2 on 2021-05-11 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'verbose_name': 'Доктор', 'verbose_name_plural': 'Докторы'},
        ),
        migrations.AddField(
            model_name='doctor',
            name='photo',
            field=models.ImageField(null=True, upload_to='doctor', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='age',
            field=models.IntegerField(verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='surname',
            field=models.CharField(max_length=120, verbose_name='Фамилия'),
        ),
    ]
