# Generated by Django 3.2 on 2021-05-11 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_auto_20210511_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='photo',
            field=models.ImageField(null=True, upload_to='doctor/', verbose_name='Фото'),
        ),
    ]
