# Generated by Django 3.2 on 2021-05-15 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnoz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='diagnoz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.diagnoz'),
        ),
    ]
